name: pypowertrain
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy >= 1.9
  - matplotlib
  - pytest
  - scikit-image
  - jupyter

  - plotly
  - pandas
  - xarray
  - dash
  - jsonpickle
  - dash-bootstrap-components